
CREATE DATABASE PROYECTO_FINAL
USE PROYECTO_FINAL

CREATE TABLE REGISTRO_VISITAS
(
ID_VISITA INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
NOMBRE NVARCHAR(30) NOT NULL,
APELLIDO NVARCHAR(256) NULL,
CARRERA NVARCHAR(250),
CORREO_ELECTRONICO NVARCHAR(250) NULL,
EDIFICIO NVARCHAR(10) NULL,
HORA_ENTRADA NVARCHAR(10) NULL,
HORA_SALIDA NVARCHAR(10) NULL,
MOTIVO_VISITA NVARCHAR(400) NULL,
AULA_LUGAR NVARCHAR(50) NULL
)

--INSERT

INSERT INTO REGISTRO_VISITAS VALUES('ROSMEIRY', 'GARABITO', 'Desarrollo de Software', 'rosmg19@gmail.com', 'Edificio 3', '12:30', '2:45', 'A recibir ayuda financiera', 'Departamento de Asistencia Financiera')
INSERT INTO REGISTRO_VISITAS VALUES('KARLS', 'JAMES', 'Multimedia', 'jenne.rosario@gmail.com', 'Edificio 2', '1:15', '3:00', 'Hacer una solitud para examen de nivelación de ingles', 'Academico')

GO 

CREATE TABLE REGISTRO_USUARIO
(
ID_USUARIO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
NOMBRE_US NVARCHAR(30) NOT NULL,
APELLIDO_US NVARCHAR(256) NULL,
FECHA_NACIMIENTO NVARCHAR(50),
TIPO_USUARIO NVARCHAR(20) NULL,
USUARIO AS ('USERS'+RIGHT('00' + CONVERT(VARCHAR,ID_USUARIO),(2)))
)

--INSERT

INSERT INTO REGISTRO_USUARIO VALUES('CHRISTOPHER', 'CHAN', '09-04-2002', 'Administrador')
INSERT INTO REGISTRO_USUARIO VALUES('EMMY', 'THOMPSON', '11-11-1999', 'General')

GO 

-- PROCEDIMIENTO BUSQUEDA 

CREATE PROC SP_BUSCARVISITAS
@BUSCAR NVARCHAR(20)
AS 
SELECT * FROM REGISTRO_VISITAS
WHERE EDIFICIO LIKE @BUSCAR + '%'
GO

-- PROCEDIMIENTO AGREGAR VISITA
CREATE PROC SP_AGREGARVISITAS
@NOMBRE NVARCHAR(30),
@APELLIDO NVARCHAR(256),
@CARRERA NVARCHAR(250),
@CORREO_ELECTRONICO NVARCHAR(250),
@EDIFICIO NVARCHAR(10),
@HORA_ENTRADA NVARCHAR(10),
@HORA_SALIDA NVARCHAR(10),
@MOTIVO_VISITA NVARCHAR(400),
@AULA_LUGAR NVARCHAR(50)
AS
INSERT INTO REGISTRO_VISITAS VALUES (@NOMBRE, @APELLIDO, @CARRERA, @CORREO_ELECTRONICO, @EDIFICIO, @HORA_ENTRADA, @HORA_SALIDA, @MOTIVO_VISITA, @AULA_LUGAR)
GO

-- PROCEDIMIENTO AGREGAR USUARIOS
CREATE PROC SP_AGREGARUSUARIOS
@NOMBRE_US NVARCHAR(30),
@APELLIDO_US NVARCHAR(100),
@FECHA_NACIMIENTO NVARCHAR(50),
@TIPO_USUARIO NVARCHAR(20)
AS
INSERT INTO REGISTRO_USUARIO VALUES (@NOMBRE_US, @APELLIDO_US, @FECHA_NACIMIENTO, @TIPO_USUARIO)
GO

-- PROCEDIMIENTO MODIFICAR VISITAS
CREATE PROC SP_MODIFICARVISITAS
@ID_VISITA INT,
@NOMBRE NVARCHAR(30),
@APELLIDO NVARCHAR(256),
@CARRERA NVARCHAR(250),
@CORREO_ELECTRONICO NVARCHAR(250),
@EDIFICIO NVARCHAR(10),
@HORA_ENTRADA NVARCHAR(10),
@HORA_SALIDA NVARCHAR(10),
@MOTIVO_VISITA NVARCHAR(400),
@AULA_LUGAR NVARCHAR(50)
AS
UPDATE REGISTRO_VISITAS SET NOMBRE = @NOMBRE, APELLIDO = @APELLIDO, CARRERA = @CARRERA, CORREO_ELECTRONICO = @CORREO_ELECTRONICO, EDIFICIO = @EDIFICIO, HORA_ENTRADA = @HORA_ENTRADA, HORA_SALIDA = @HORA_SALIDA, MOTIVO_VISITA = @MOTIVO_VISITA, AULA_LUGAR = @AULA_LUGAR
WHERE ID_VISITA = @ID_VISITA
GO
